### ISSUE TITLE
Issue in run.sh

### ISSUE THREAD

**Issue by musta-zirari** [alievk/avatarify-python#216]
I have installed everything but finally I faced this issue : 

`
bash run.sh        
[1592038869.754661] Loading Predictor
/home/mypc/Desktop/avatarify/afy/predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
[1592038894.081497] Trying camera with id 0
[1592038896.782520] Trying camera with id 1
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[1592038896.805590] Camera with id 1 is not available
[1592038896.805680] Trying camera with id 2
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video2): can't open camera by index
[1592038896.805852] Camera with id 2 is not available
[1592038896.805911] Trying camera with id 3
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video3): can't open camera by index
[1592038896.806050] Camera with id 3 is not available
QObject::moveToThread: Current thread (0x5600acebab90) is not the object's thread (0x5600acff55d0).
Cannot move to target thread (0x5600acebab90)

run.sh: line 61:  9609 Segmentation fault      (core dumped) python afy/cam_fomm.py --config $FOMM_CONFIG --checkpoint $FOMM_CKPT --virt-cam $CAMID_VIRT --relative --adapt_scale $@
`

Where is the problem?

**Comment by mintmaker** [comment]
It's a bit late, but Segmentation fault normally means that there is not enough memory to run the program. So you can't run avatarify on that machine.

**Comment by JohanAR** [comment]
Please try again with the latest version of Avatarify
