### ISSUE TITLE
Finally i made it work

### ISSUE THREAD

**Issue by KKiohd** [alievk/avatarify-python#268]
**Describe the bug**

the bug was that some lines aren't clear
i fixed changing the code

**To Reproduce**

donwload and run it, you will experience 6-7 steps of wrong understanding of the script.

SOLUTION.
at least for me

open miniconda
download git (follow the step in the main page)
download the assets via git code
download the neural network (place it the main folder, follow the step of the main page)
download (https://github.com/alievk/first-order-model)

run the scrip to install the asset avatarify
move the neural network on the main folder
move the "module" folder in the main avatarify folder

then copy the content of this folder in the "afy" folder
[copy this in afy.zip](https://github.com/alievk/avatarify/files/5075624/copy.this.in.afy.zip)

then try to run it. with the command run_windows.bat
if it shows an error of wrong attribute
find the location of your miniconda program 
then find there  ...\envs\avatarify\Lib\site-packages\torch\nn\modules
and put this file in it
[module.zip](https://github.com/alievk/avatarify/files/5075631/module.zip)

try to run it. with the command run_windows.bat
now it should work fine.

to change the avatar (photos)  you need to close and re run it again

**Comment by littleqing0914** [comment]
hello，Did you meet the question "Downloading face detection CNN, please wait..." when run "bash run.sh"?

**Comment by Waykon12** [comment]
KKiohd please does your avatar shakes and can you make a video of how you did your avatarify

**Comment by JohanAR** [comment]
This is info is out of date, closing issue

**Comment by Waykon12** [comment]
I can’t seem to get avatarify to work again . 

This is the message I get 
Loading PredictorTraceback (most recent call last) :File"afy/cam fomm.py"line 216, in ‹module>from afy import predictor localImportError: cannot import name"predictor local'from"afy'(unknown location)

**Comment by debrah01** [comment]
> This is info is out of date, closing issue

Does is it still work?

**Comment by Brownlyn-Codelabs** [comment]
Get your installation, easy step by step tutorial here.
anyDesk or come in person.
call 0552366834 or whatsapp.
Thank you.
avatarify, DeepFake, Voice cloning. all here.
