### ISSUE TITLE
What should I do with this error?

### ISSUE THREAD

**Issue by liukai1314** [alievk/avatarify-python#291]
error：
[1602264806.110559] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 193, in <module>
    from afy import predictor_local
  File "C:\Users\yytrftt\avatarify\afy\predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules'

Follow the steps all. After referring to the previous question, after several attempts, it is still the same.
I really want to experience it. I hope anyone who is free can provide some guidance.
Thank you

**Comment by alievk** [comment]
Could you post the installation log here?

**Comment by jielingao** [comment]
I have the same problem 
![image](https://user-images.githubusercontent.com/45685396/110434850-477e5c00-80ed-11eb-8887-67465703bf31.png)

**Comment by JohanAR** [comment]
please use issue #198 instead

I'm closing this as duplicate since it contains no new information (we need install logs to figure out what happened :))

**Comment by badboi017** [comment]
still having same issues plz can you help
