### ISSUE TITLE
Error during the install.bat

### ISSUE THREAD

**Issue by CheeseHotdog** [alievk/avatarify-python#302]
(avatarify) D:\DeepFakeTutorial\avatarify-windows>REM ###FOMM###

(avatarify) D:\DeepFakeTutorial\avatarify-windows>call git clone https://github.com/alievk/first-order-model.git fomm
'git' is not recognized as an internal or external command,
operable program or batch file.

(avatarify) D:\DeepFakeTutorial\avatarify-windows>call pip install -r fomm/requirements.txt

**Comment by JohanAR** [comment]
Looks like you haven't installed git. Have you followed the install instructions? https://github.com/alievk/avatarify#windows
