### ISSUE TITLE
Using androidcam instead of webcam possible ?

### ISSUE THREAD

**Issue by Mark-papi** [alievk/avatarify-python#304]
is it possible to set the android camera as the main camera in the program so i can use that instead of my very bad webcam?
thanks for any response related to my problem.

**Comment by Mark-papi** [comment]
need to NOTE that im using arch linux manjaro

**Comment by Mark-papi** [comment]
i solved it just by downloading the app as well in the phone, but now i have this 
![Screenshot_2020-11-13_13-08-09](https://user-images.githubusercontent.com/12816482/99050406-c381f080-25a0-11eb-9b72-1af4931d7b05.png)

**Comment by Mark-papi** [comment]
any idea on how to fix those beautifull green lines?

**Comment by JohanAR** [comment]
I got this running, but I had to tell v4l2loopback to create 2 devices manually.

```
# unload v4l2loopback if you have loaded it before
modprobe -r v4l2loopback

# probe it with additional settings
modprobe v4l2loopback devices=2 video_nr=9  exclusive_caps=1 
```

This creates both /dev/video9 which is avatarify's default and the second device will use the first available number, which for me was /dev/video0. After this I just started DroidCam and avatarify and everything just worked

**Comment by JohanAR** [comment]
Did you manage to get it running?

I'm guessing the green lines could be an encoding mismatch. I don't remember if DroidCam let me choose encoding, but have you checked if the video looks ok if you open it in VLC or something instead?

I haven't looked into it yet, but maybe it would be possible to add an option to force an encoding in case OpenCV fails to autodetect it (which I assume it tries to)
