### ISSUE TITLE
Issues running

### ISSUE THREAD

**Issue by jacke123** [alievk/avatarify-python#314]
I can run the instalation and it runs fine but when I try to run it from the file it says Python permision is denied and it gives me this

Creating virtual camera /dev/video9 (sudo privelege required)
scripts/create_virtual_camera.sh: line 8: sudo: command not found
bash: conda: command not found
bash: /etc/profile.d/conda.sh: No such file or directory
bash: conda: command not found
bash: /c/Users/linda/AppData/Local/Microsoft/WindowsApps/python: Permission denied
/usr/bin/bash: Exit 126.

**Comment by JohanAR** [comment]
Are you trying to run Avatarify in WSL? Avatarify depends on the v4l2loopback kernel module, and I'm not sure you kan have kernel modules in WSL..

Have you tried running it in Windows instead?
