### ISSUE TITLE
Nvidea Quadro 2000m

### ISSUE THREAD

**Issue by Twizdav** [alievk/avatarify-python#356]
Can i use nvidea Quadro 2000m to run avatarify smoothly

**Comment by alievk** [comment]
If you provide specs (like CUDA cores and memory) it would be easier to predict.

**Comment by Twizdav** [comment]
CUDA:	2.1
CUDA cores:	192
ROPs:	16
Texture units:	32
RAMDACs:	400 MHz

**Comment by Twizdav** [comment]
Memory

DDR3 PC3-10600 SDRAM (1,333 MHz)Two or four SODIMM slots supporting dual-channel memory2GB, 4GB and 8GB SODIMMsMaximumUpgradeable to 32GB with (4) 8GB SODIMMsDual-channelMaximized dual-channel performance requires SODIMMs of the same size and speed in both memory slots

**Comment by alievk** [comment]
This is very old GPU, I'm afraid it would work like a slide show.

You would need something live Nvidia GeForce GTX 1650M to have a decent performance. This issue thread may be interesting https://github.com/alievk/avatarify/issues/168

**Comment by Twizdav** [comment]
Thank you,
