### ISSUE TITLE
I can't find nvidia gpu that works

### ISSUE THREAD

**Issue by darellwest** [alievk/avatarify-python#357]
hi, I have a hp pavilion Laptop 15-cc1xx that came with intel (R) UHD Graphics 620 GPU and Intel(R) CORE is-8250U CPU. I can't seem to find a NVIDIA GPU that works. I have tried nvidia GeForce 940MX as it is the recommended GUP for the laptop but I can't seem to find one that works...always says not compactible.
Is there a way to go around this?
avatarify works but it is almost impossible to use because the avatar is so slow.

**Comment by JohanAR** [comment]
Not sure if I misunderstand you, but a GPU is a piece of electronics inside your laptop, it's not normally something you search for. If your laptop only says "intel (R) UHD Graphics 620 GPU" it means that you have an Intel GPU. Some laptops have both an Intel GPU and an Nvidia GPU, but that depends on what you bought. The HP pavilion 15-cc1xx has been sold both with only Intel and with Intel+Nvidia, so I can't tell from just the model number if there is an Nvidia GPU in your laptop.

If you try to install Nvidia drivers and it says not compatible there is a risk that you don't have an Nvidia GPU. You can probably check what you have in Windows device manager or something, but you'll have to google that, I don't use Windows myself.

 It is usually not possible to upgrade the GPU after you have bought a laptop. I think you can buy an external GPU for a modern laptop with usb-c, but I really don't know anything about that.

**Comment by alievk** [comment]
GeForce 940MX is not powerful enough. You would need something like GeForce GTX 1650M to have a decent performance. 

I guess you have something like ~5 frames per second, since 940MX has 384 cores and 1650M has 1024 cores (~3x more), which features 18 FPS. You may want to check this #168.
