### ISSUE TITLE
Apprently everything was installed correctly, but I got OSerrors?...

### ISSUE THREAD

**Issue by leapsieg** [alievk/avatarify-python#359]
So! I installed this for the first time, some of the things that were being downloaded stopped at 43% while the others continued so I decided to reinstall it again... Cool! Apparently everything went smoothly, no errors, no nothing, however, when I launch run_windows.bat, I get OSerror WinError 1455 and after reopening it OSerror WinError 1450. Very weird, in my opinion. 

Any help would be appreciated! I have the installation log still open, so ask for _anything_ that you may need to help me fixing this problem! Just want to point out I am not very experienced with all of this... Thanks, anyways! :))

Errors screenshots:
https://prnt.sc/y2mggl
https://prnt.sc/y2no7a 
(I'll translate whatever is on the picture that you may need translated)

**Comment by JohanAR** [comment]
I'm not the Windows expert, but it looks like it first says that it can't find the Avatarify conda environment, so I would guess that the OSError is just a side effect of that. The conda environment is supposed to be created by install_windows.bat, so maybe you could try running steps 3 and 4 from the installation again. I think it's likely that the install log says something about this if it fails to create the environment, so it would help if you could save the whole log to a text file and attach it to the issue
