### ISSUE TITLE
Nothing happens when using Custom Avatar Button

### ISSUE THREAD

**Issue by BobJoeman21** [alievk/avatarify-python#371]
**Describe the bug**
When I press the Open Image File in the Windows app and choose a picture, nothing happens.

**To Reproduce**
Press the Open Image File and see if something happens.

**Info (please complete the following information):**
 - OS (e.g., Linux): Windows
 - GPU model: GTX 1050
 - Any other relevant information: 
 - I think the problem might just be that I'm using bad pictures, but IDK.

**Comment by BobJoeman21** [comment]
I can now confirm it is definitely because I was using bad pictures. When I use a good picture, it works fine. I think you should add some notification if the image being used isn't acceptable, and maybe settings that allow the user to point out the face in a given image so that they have more options.

**Comment by JohanAR** [comment]
The Windows app has now been released as [Avatarify Desktop](https://github.com/alievk/avatarify-desktop) in a separate repo.

Nice that you figured it out! Please add your feature requests as an issue in the Avatarify Desktop repo
