### ISSUE TITLE
avatarify cam still shows up after deinstalling avatarify

### ISSUE THREAD

**Issue by FurriousFox** [alievk/avatarify-python#374]
**Describe the bug**

I installed avatarify, i deinstalled avatarify (using the deinstaller), but now the (unasable) avatarify cam still shows up

**To Reproduce**

1. install avatarify
2. start avatarify
3. deinstall avatarify using the deinstaller
4. check if the cam still shows up

**Info (please complete the following information):**
 - OS (e.g., Linux): Windows
 - GPU model: Doesn't matter

**Comment by JohanAR** [comment]
Are you talking about the Python version of Avatarify (which is located in this github repo) or the Windows App?

I'm not on Windows myself, but could it be the OBS VirtualCam that you probably installed at the same time as Avatarify?

**Comment by klokwert** [comment]
the windows app, and the obs VirtualCam was already installed from about few months ago

**Comment by JohanAR** [comment]
maybe @alievk knows more about this

**Comment by klokwert** [comment]
maybe

**Comment by JohanAR** [comment]
I think he's been busy :/ The Windows app has now been released as [Avatarify Desktop](https://github.com/alievk/avatarify-desktop) in a separate repo. Please open an issue in that repo if you still have this problem, there it will be seen by other users of the app so hopefully someone will be able to help
