### ISSUE TITLE
Windows App (Beta) The app does not open

### ISSUE THREAD

**Issue by liel0983** [alievk/avatarify-python#392]
i try to do what you say to do but when ו was looking "Avatarify" It did not find me what it was supposed to find (Attached picture)
[![2021-03-07-005033.png](https://i.postimg.cc/tJRbTctb/2021-03-07-005033.png)](https://postimg.cc/xJZhpt4p)
and i try to run with administrator and And nothing happened not know what to do Maybe you can help
i have gtx 1660 ti

**Comment by monkeydust** [comment]
same issue - its running in taskmanager but nothing pops up no errors or anything even when I run from cmd line

**Comment by JohanAR** [comment]
> same issue - its running in taskmanager but nothing pops up no errors or anything even when I run from cmd line

Please use the new avatarify-desktop repo for issues related to the Windows App, it is more likely that someone will be able to help you there: https://github.com/alievk/avatarify-desktop
