### ISSUE TITLE
Accidently selected wrong camera

### ISSUE THREAD

**Issue by TheBrist** [alievk/avatarify-python#393]
I was installing the program and everything went fine, but when It got to the screen of selecting a camera I chose a virtual camera that I had installed instead of my actuall web cam. Now It only shows some weird stuff on the camera and I don't know how to change it. So how can I go back to the camera selecting screen?

**Comment by NOobhacke102** [comment]
Repair the application

**Comment by TheBrist** [comment]
> Repair

wdym?

**Comment by JohanAR** [comment]
There is no going back, but it should ask you again if you restart the program

**Comment by Mikaeel10** [comment]
Try to change your cam ID in the file "cam.yaml". Open it with a notepad. Try several different ID's

**Comment by JohanAR** [comment]
Assuming solved since it's been several months without new info
