### ISSUE TITLE
LinuxMint 5.4.0-72 crashes after 30 secs running and hangs machine.

### ISSUE THREAD

**Issue by retrocrypta** [alievk/avatarify-python#406]
My system it's a Linunx Mint 20.1 Ulyssa 64 bit with Kernel 5.4.0-72-generic x86_64
CPU: Intel® Core™ i5-4460 CPU @ 3.20GHz × 4 
12 GB RAM and Nvidia GeForce 1050Ti with 4 GB GPU RAM. 768 cuda cores.

After I installed avatarify-python following the instructions, it worked perfectly for two days. On the third day and executing, once I select the face with the X key, after 30 seconds there is a hang that leaves the machine in a catatonic state.  All systems comes black and need to reset or power cycle.

When I run the avatarify I get 15 fps. Everything seems to be OK and no problems with the software.

**To Reproduce**

I think the memory of the python process is too high: 3200 MB
¿ May be a problem of out of memory ? 

I have reviewed the drivers, the cuda software and everything is correct. The problem is reproduced every time I run avartarify-Python. After 30 seconds running as well, suddenly there is a black screen and again and again.

Linux: nvidia-smi -L
GPU 0: NVIDIA GeForce GTX 1050 Ti (UUID: GPU-785057a5-09e9-ae78-3c31-3e6a787cef47)
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   58C    P0    N/A / 120W |    231MiB /  4034MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1317      G   /usr/lib/xorg/Xorg                220MiB |
|    0   N/A  N/A      2075      G   compiz                              5MiB |
|    0   N/A  N/A      3635      G   qv4l2                               2MiB |
+-----------------------------------------------------------------------------+

conda info

     active environment : avatarify
    active env location : /home/xxx/miniconda3/envs/avatarify
            shell level : 1
       user config file : /home/xxx/.condarc
 populated config files : /home/xxx/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.3=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/xxx/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/xxx/miniconda3/pkgs
                          /home/xxx/.conda/pkgs
       envs directories : /home/xxx/miniconda3/envs
                          /home/xxx/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.4.0-72-generic linuxmint/20.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

conda list
# packages in environment at /home/xxx/miniconda3/envs/avatarify:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blosc                     1.20.1               he1b5a44_0    conda-forge
brotli                    1.0.9                he1b5a44_3    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
chardet                   4.0.0                    pypi_0    pypi
charls                    2.1.0                he1b5a44_2    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py37h4abf009_1    conda-forge
dask-core                 2021.4.1           pyhd8ed1ab_0    conda-forge
decorator                 5.0.7              pyhd8ed1ab_0    conda-forge
face-alignment            1.3.3                    pypi_0    pypi
freetype                  2.10.4               h7ca028e_0    conda-forge
fsspec                    2021.4.0           pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
idna                      2.10                     pypi_0    pypi
imagecodecs               2020.5.30        py37hda6ee5b_1    conda-forge
imageio                   2.9.0                      py_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jxrlib                    1.1                  h516909a_2    conda-forge
kiwisolver                1.3.1            py37hc928c03_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libaec                    1.0.4                he1b5a44_1    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.5.0               h14aa051_19    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h4f3a223_6    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libzopfli                 1.0.3                he1b5a44_0    conda-forge
llvmlite                  0.36.0                   pypi_0    pypi
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
matplotlib-base           3.3.3            py37h4f6019d_0    conda-forge
msgpack                   1.0.2                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
networkx                  2.5                        py_0    conda-forge
numba                     0.53.1                   pypi_0    pypi
numpy                     1.19.0           py37h8960a57_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.2.0.34                 pypi_0    pypi
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1k               h27cfd23_0  
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pillow                    8.0.1            py37h63a5d19_0    conda-forge
pip                       21.0.1           py37h06a4308_0  
pyfakewebcam              0.1.0                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.7.10               hdb3f193_0  
python-blosc              1.7.0           py37hf484d3e_1001    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pywavelets                1.1.1            py37h161383b_3    conda-forge
pyyaml                    5.3.1            py37hb5d75c8_1    conda-forge
pyzmq                     20.0.0                   pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
scikit-image              0.17.2           py37h10a2094_4    conda-forge
scipy                     1.5.3            py37h8911b10_0    conda-forge
setuptools                52.0.0           py37h06a4308_0  
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.35.4               hdfb4753_0  
tifffile                  2020.12.8          pyhd8ed1ab_0    conda-forge
tk                        8.6.10               hbc83047_0  
toolz                     0.11.1                     py_0    conda-forge
torch                     1.8.1                    pypi_0    pypi
tornado                   6.1              py37h4abf009_0    conda-forge
tqdm                      4.60.0                   pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.4                   pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h6597ccf_2    conda-forge

echo $PYTHONPATH : NONE

echo $PATH
/home/xxx/miniconda3/envs/avatarify/bin:/usr/local/cuda-11.3/bin:/home/xxx/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-15-oracle/bin:/usr/lib/jvm/java-15-oracle/db/bin

NO LOGS registrered, the crash does not log anything.

**Comment by JohanAR** [comment]
It runs on systems with worse specs, so I don't think that should be the issue. Either way it should either refuse to start, or have really low fps, if you don't have enough computing power. It shouldn't crash your computer..

Have you tried rolling back to an older GPU driver? I'm using 460.73.01 though I have a GTX1080

If it's not the driver it could be a hardware issue, for example overheating or unstable power. Have you checked so the GPU fan isn't full with dust? :) What type of PSU have you got? Tried running any other GPU benchmarks or processing intensive tasks?

**Comment by retrocrypta** [comment]
Hi, thanks very much for your support.
I have been checking the PC and everything seems to be clean and with a good look.

I have taken the opportunity to change the power supply for another that I have as a spare. I have turned on and tested, the result is that it does not crash. Now it seems to be back to normal.

Another thing that I have noticed is that instead of consuming 3.2GB of memory now it remains at 2.2GB of GPU. 

In any case, I rule out that it is a software / driver problem. I'm going to see how it behaves with the power supply, which by the way, both are 600W. 

Thanks very much. Regards.

**Comment by JohanAR** [comment]
No problem, let's hope it stays like this! Lucky you had a spare PSU to test with

It's been a while since built a computer, but IIRC in addition to looking at PSU total wattage it matters how many amps it can deliver on a single 12V rail. And of course cheaper PSUs might not deliver what they promise :)
