### ISSUE TITLE
Error when trying to run on a Jetson Nano

### ISSUE THREAD

**Issue by jasmine653** [alievk/avatarify-python#407]
**Describe the bug**

I am trying to get avatarify-python to work on a Jetson Nano. I followed the contrib/jetsontx2 branch install instructions (but with newer versions of PyTorch, torchvision and OpenCV). 

I tested the camera (IMX219-170) previously with an OpenCV example and it works. After successfully installing (install_jetson.sh), when I try to run avatarify I get errors.

**Info**

<ins>Hardware:</ins>
NVIDIA Jetson Nano Developer Kit – B01
IMX219-170 Camera

<ins>Versions:</ins>
L4T 32.5.1 (Jetpack 4.5.1)
OpenCV (version 4.4.0)
PyTorch (version 1.8.0)
torchvision (version  0.9.0)
Gstreamer is enabled (version 1.14.5)
Magma (version 2.5.4)

**Logs**

```
Loading Predictor
Key 1: ./avatars/einstein.jpg
Key 2: ./avatars/eminem.jpg
Key 3: ./avatars/jobs.jpg
Key 4: ./avatars/mona.jpg
Key 5: ./avatars/obama.jpg
Key 6: ./avatars/potter.jpg
Key 7: ./avatars/ronaldo.png
Key 8: ./avatars/schwarzenegger.png
[ WARN:0] global /tmp/pip-install-rxf4alk5/opencv-python_18b9ab20120f4386b9470aff890a1224/opencv/modules/videoio/src/cap_gstreamer.cpp (1761) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global /tmp/pip-install-rxf4alk5/opencv-python_18b9ab20120f4386b9470aff890a1224/opencv/modules/videoio/src/cap_gstreamer.cpp (888) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /tmp/pip-install-rxf4alk5/opencv-python_18b9ab20120f4386b9470aff890a1224/opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global /tmp/pip-install-rxf4alk5/opencv-python_18b9ab20120f4386b9470aff890a1224/opencv/modules/videoio/src/cap_v4l.cpp (1004) tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:1] global /tmp/pip-install-rxf4alk5/opencv-python_18b9ab20120f4386b9470aff890a1224/opencv/modules/videoio/src/cap_v4l.cpp (1004) tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 159, in <module>
    cap.start()
  File "/home/nano/avatarify/afy/videocaptureasync.py", line 86, in start
    raise RuntimeError(f"Failed to succesfully grab frame from the camera (timeout={WARMUP_TIMEOUT}s). Try to restart.")
RuntimeError: Failed to succesfully grab frame from the camera (timeout=10.0s). Try to restart.
```
**Other**

I took a peak into the code and the gstreamer errors appear in avatarify/afy/videocaptureasync.py when 
```self.cap = cv2.VideoCapture(self.src)```  is called on line 15. How do I fix this?

**Comment by JohanAR** [comment]
I don't think anyone of us has a Jetson Nano so I'm afraid we can't help you much here.

I can only offer some general tips:
1. Increase WARMUP_TIMEOUT, maybe 10 seconds is too short?
2. Make sure Avatarify is actually using the OpenCV version that you think it is
3. Is exactly the same command working in that OpenCV example, using exactly the same versions?
4. The branch you're on is 13 years old, perhaps something else has changed. Try merging with master

**Comment by jasmine653** [comment]
Increasing WARMUP_TIMEOUT fixed the error! I increased it to 20 seconds for reference.

I then got another error which was fixed by replacing ```self.src``` in ```self.cap = cv2.VideoCapture(self.src)``` with a GStreamer pipeline string and cv2.CAP_GSTREAMER.

Thank you!
