### ISSUE TITLE
how should i use this program. '

### ISSUE THREAD

**Issue by acemonster03** [alievk/avatarify-python#408]
**Describe the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by JohanAR** [comment]
The first step is to read [the project description](https://github.com/alievk/avatarify-python), it will then tell you the next step.

If you're using Windows, then [Avatarify Desktop](https://github.com/alievk/avatarify-desktop) is probably more suited for you, it's made to be much easier to install and use.
