### ISSUE TITLE
only 256*256 image support?

### ISSUE THREAD

**Issue by rainynight100** [alievk/avatarify-python#410]
Is this project only predict  pic  with shape (256,256,3)? if i want to predict a pic (500,500,3) what should I do ?

**Comment by JohanAR** [comment]
You'd need to train a new dataset with the resolution you want to use, the [First Order Motion Model](https://github.com/AliaksandrSiarohin/first-order-model) project has instructions for that. After that it shouldn't be much more work than changing all the image size constants in avatarify-python
