### ISSUE TITLE
NVIDIA GEFORCE 940MX

### ISSUE THREAD

**Issue by SamDan1324** [alievk/avatarify-python#412]
Whenever I select any of the avatars from the Avatarify desktop it freezes and after sometime the Avatarify desktop launcher closes..
Am guessing it's my graphics card (am using Nvidia GeForce 940 MX) if that's the case can I upgrade the graphics card to GTX 1080 using the GEFORCE software or I must change the graphics card(hardware)

**Comment by JohanAR** [comment]
Please open a ticket with [Avatarify Desktpo](https://github.com/alievk/avatarify-desktop) if that's what you're using, this repository is for the older and slightly less user-friendly Avatarify Python

I don't know if the "MX" means that your GPU is missing some feature necessary to run Avatarify, most of the time it only runs with very low fps if your GPU is too slow.

And no, you can't turn your graphics card into a different more powerful graphics card using software :)

**Comment by SamDan1324** [comment]
![IMG-20210705-WA0005](https://user-images.githubusercontent.com/85712242/124500723-2afee180-ddb8-11eb-80da-98bfac453afe.jpg)

**Comment by SamDan1324** [comment]
That's what am referring to in the above screenshot

**Comment by JohanAR** [comment]
Not really sure what I'm supposed to look for, it's a little blurry but all I can see is that you have a Geforce 940MX

Graphics cards aren't like Teslas, where you can unlock more power by paying a fee and downloading an update, if that's what you're wondering. If you want a GTX 1080 you must buy new hardware. But I think the 940MX is a laptop card, and if you have a laptop it might not be physically possible to upgrade the graphics.

**Comment by srinivas12504** [comment]
Okay heres the thing, the mx series graphics cards are the low end ones that are used in ultrabooks or thin and light notebooks.  And no, you cannot just download a new graphics card, you need to change the hardware, also, you cannot do that on a laptop, as the processors are soldered onto the motherboard. 940MX is not for heavy usage, so please be careful.

**Comment by SamDan1324** [comment]
Thanks Guys..
Is NVIDIA GEFORCE GTX 1080 graphics card a good buy?
Which of the the GTX is faster and smoother

**Comment by JohanAR** [comment]
First of all, do you own a stationary computer that can actually use a graphics card? If you only have a laptop the answer is "No, it's not a good buy, because you will not be able to use it".

> Is NVIDIA GEFORCE GTX 1080 graphics card a good buy?

It's several years old now, but it's not a bad card. It could be a good buy if you can get one second hand cheap. I'm currently using a GTX1080 that I got from a friend, it is definitely fast enough to run Avatarify.

> Which of the the GTX is faster and smoother

All GTX cards are old, NVidia stopped making them several years ago. But to answer your question, I think the fastest one was GTX1080 Ti (from 2018).

The current Nvidia cards are called RTX, and I believe the "fastest and smoothest" would be a RTX 3090

**Comment by srinivas12504** [comment]
If you can get a GTX 1080 for second hand then, it's fine. But do you have a Desktop with a Cabinet? Because if you don't , you have to buy an entire system, you cannot attach to your laptop, until you can buy a external gpu connected through high data rate transfer port like thunderbolt 3.

**Comment by SamDan1324** [comment]
INSTANT REPLY NEEDED
Thanks guys I really appreciate all your contributions..

Laptop name - ZBook 15 G3
Nvidia Quadro M1000m

CURRENTLY AT THE STORE is anyone using this kind of PC for Avatarify?

**Comment by srinivas12504** [comment]
The QUADRO are for 3D designing like CAD, but not for training neural networks. The TESLA cards are actually used in industry standard for training neural networks. so yeah no, please do not buy this. Here is a Kaggle form for your reference.

https://www.kaggle.com/general/11332

**Comment by SamDan1324** [comment]
Thanks @srinivas12504 @JohanAR 
You guys have really helped me here, I really appreciate..

Thanks @srinivas12504  I won't buy it again, I will go for RTX 3090
