### ISSUE TITLE
error run_windows.bat

### ISSUE THREAD

**Issue by redsky5550** [alievk/avatarify-python#457]
after installing the script code , and then downloading the network weight , i placed it in the avatarify folder didnt unpack it , then came back to anaconda promot and input the code , run_windows.bat  , after loading for a while it comes as filenotfounderror: [errno2] no such file or directory : 'vox-advcpk.pth.tar' .. can you please help me out with this issue 
![IMG_1320](https://user-images.githubusercontent.com/114403600/192266398-202198db-51ac-4915-b3fe-f9095d7ad663.jpg)

**Comment by JohanAR** [comment]
This is a research project that alievk made available for other people to use, it's not a normal Windows program that you just unpack and run. You really have to read the documentation and follow the instructions.

If you were expecting something else, maybe [Avatarify Desktop](https://github.com/alievk/avatarify-desktop) or [avatarify.ai](https://avatarify.ai/) is more what you were looking for?

**Comment by Michael-cyber-web** [comment]
[1686239325.718170] Loading Predictor

Traceback (most recent call last): File "afy/cam fomm.py", line 218, in <module>
**predictor_args
File "C:\Users\nzeme\avatarify-python\afy\predictor_local.py", line 49, in __init__
self.fa face alignment.FaceAlignment (face_alignment. LandmarksType._2D, Flip input=True, device=self.device) File "C:\Users\nzeme\miniconda3/envs\avatarify\lib\enum.py", line 354, in _getattr_ raise AttributeError(name) from None
AttributeError: 2D

**Comment by Papimalay** [comment]
This is exactly same problem and facing and i been doing it for days yet not working out, i need help.. i feel so frustrated

**Comment by engrmarcel** [comment]
> [1686239325.718170] Loading Predictor
> 
> Traceback (most recent call last): File "afy/cam fomm.py", line 218, in **predictor_args File "C:\Users\nzeme\avatarify-python\afy\predictor_local.py", line 49, in **init** self.fa face alignment.FaceAlignment (face_alignment. LandmarksType._2D, Flip input=True, device=self.device) File "C:\Users\nzeme\miniconda3/envs\avatarify\lib\enum.py", line 354, in _getattr_ raise AttributeError(name) from None AttributeError: 2D

@Papimalay have you gotten solution to the above issue?

**Comment by Papimalay** [comment]
No, not yet. I haven’t.. someone told me because my laptop don’t have
inbuilt NVIDIA DRIVER , then asked me to buy laptop with  this info below

Nvidia GeForce rtx 3060 16 Gb dedicated 16gb or 32gb ram Any hard disk
drive any rom any size

But my worried is what if I buy another laptop and still didn’t work ?
