### ISSUE TITLE
afy/cam_fomm.py", line 73 error

### ISSUE THREAD

**Issue by Donvickins** [alievk/avatarify-python#459]
<img width="974" alt="Screenshot 2022-09-28 at 4 03 49 PM" src="https://user-images.githubusercontent.com/49022078/192815340-b8ef36a9-898e-43d8-bddd-e50f2d527489.png">
I get this crash error when I try to start the program. I have installed the dependencies using scripts/install_mac.sh.

**Comment by davidlorex** [comment]
Don't mess up your system . You have a mac . I do not expect do this on your system processor.  
Advice . Run this using google colab .

**Comment by Donvickins** [comment]
Using google colab it gets stuck on recieving...
I tried using AWS, but I'm not too familiar with. I got stuck at configuring tcp.

I will appreciate If you could show me how to use google colab.

**Comment by Ejire2dworlf** [comment]
I'm having the same trouble but it's on Windows.  How did you go about it.
