### ISSUE TITLE
Avatarify

### ISSUE THREAD

**Issue by Pige0n3579** [alievk/avatarify-python#462]
Good evening admin. I am new here please where can I download vox-adv-cpk.pth for avatarify. Kindly help me

**Comment by JohanAR** [comment]
Links are provided in the installation instructions, which you should be following if want to have any chance of running this software.

**Comment by Pige0n3579** [comment]
I did but not valid

**Comment by JohanAR** [comment]
Just tested them and at least 2 of the download locations work perfectly fine.

**Comment by Pige0n3579** [comment]
OK then, thanks alot for been so kind JohanAR.. I'ppreciate

**Comment by beloyal7778** [comment]
please i do need help with avatarify after the code it could not be successfully installed anyone to help me out please
