### ISSUE TITLE
Cam and Avatarify window does not open. Please help

### ISSUE THREAD

**Issue by ricosta83** [alievk/avatarify-python#472]
![image](https://user-images.githubusercontent.com/117032254/201716847-e1997ff4-be8d-4912-961b-a8a96af200ba.jpeg)

**Comment by JohanAR** [comment]
Sorry I don't have any good answer for you. Could be that your camera isn't supported by OpenCV or something

**Comment by Gate1990** [comment]
How can I bypass solving environments
