### ISSUE TITLE
Low fps on GTX 1660 ti max Q design 

### ISSUE THREAD

**Issue by Lednem** [alievk/avatarify-python#475]
I have done the python installation on my dell laptop with NVIDIA GeForce GTX 1660ti max Q  with 6gb dedicated and the latest NVIDIA drivers and I only get an fps of 3.8 with little to no movement of the mouth even with perfect lighting conditions. I need an assistance with this.

**Comment by JohanAR** [comment]
Regarding it not following your movement: Are you close enough to the camera so that your face fills most of the image? Did you press "x" to calibrate, when your face was aligned with the target image?

If you press "o" you should be able to see the output of the face detector. Do the lines align with your facial features?

**Comment by Lednem** [comment]
Okay, thanks. That solved the problem. I appreciate the assistance.

**Comment by JohanAR** [comment]
Glad to hear that. Closing the issue since it's solved, re-open it if there was something more

**Comment by uwuigbe** [comment]
![image](https://user-images.githubusercontent.com/121306611/209365659-58fc3adc-ccaa-49d4-a89a-084148bdc750.jpeg)

**Comment by uwuigbe** [comment]
I'm having same laptop but I get these errors

**Comment by Lednem** [comment]
Am not understanding your issues properly, but from the screen am seeing,
the avatars should already be displaying. Let me know more details so I can
try to assist you.

**Comment by Donskate** [comment]
Am using RTX 3050ti   
  
32gig ram   
  
11th generation   
  
1tb ssd drive   
  
  I have run avatarify several times still not working   
  
  
  
  
  
  
  

  
  
>

**Comment by Lednem** [comment]
Have you tried the desktop version of the python seem to be giving you
issues?

**Comment by Lednem** [comment]
Yes, It is working but it depends on your system. I've installed in many
system so I discovered it requires a higher cuda enabled system. What is
the specification of your system?
