### ISSUE TITLE
Avatarify doesn't install anymore on windows. Tried 2 laptops and got the same results.

### ISSUE THREAD

**Issue by withlove574** [alievk/avatarify-python#481]
![image](https://user-images.githubusercontent.com/115517246/206891945-88b0ddf2-b9ea-4b31-915d-60969449a3d1.jpeg)

**Comment by geekedpriest** [comment]
How about Mac book sir is there a tutorial for Mac book ? I really need your help

**Comment by danxtg** [comment]
i can help you but it will cost $200

**Comment by geekedpriest** [comment]
@danxtg  Will you do for $100 and i you have to send me your WhatsApp number or something

**Comment by JohanAR** [comment]
Deleting all messages not related to this issue. If any of the offending posters read this: Soliciting money from other users is not allowed here, consider this is your second warning.

@withlove574 this isn't a good issue report, which will make it very difficult for anyone to help you. Do a clean installation of avatarify-python, making sure to follow the instructions. If it still isn't working, look up how to A) copy text from the terminal and B) how to format text as code on github to make it readable.

**Comment by withlove574** [comment]
Got it done. Thanks a lot🙏

**Comment by jacobgrant446** [comment]
Withlove574 how did you get yours working again? I’m having same issues

**Comment by JohanAR** [comment]
@withlove574 nice! Closing this issue then. Re-open it if I misunderstood you and there is still something that isn't working for you.

@jacobgrant446 since they thanked me I would guess that the thing I said worked: "Do a clean installation of avatarify-python, making sure to follow the instructions"
