### ISSUE TITLE
Done

### ISSUE THREAD

**Issue by Jessynaija** [alievk/avatarify-python#483]
Done

**Comment by JohanAR** [comment]
It's downloading files from github, it is done when it goes all the way to 100%. If it gets stuck you might have some network issue, or your disk is full or something.

**Comment by danxtg** [comment]
am having same issues, i have wiped my Pc already.
still no changes

**Comment by danxtg** [comment]
i have the solution now, but will cost $200

**Comment by JohanAR** [comment]
@danxtg I wouldn't mind if you offered paid technical support to help someone 1-on-1, but demanding money to share your solution is pretty scummy IMO. Keep in mind that this software exists because other people, who spent significantly more time on it than you, contributed their work for free.

**Comment by danxtg** [comment]
It's cool if you find it scummy. I can't make you more convinced

**Comment by geekedpriest** [comment]
@danxtg whats your cost.... I don't mind paying ...![image](https://user-images.gith ubusercontent.com/120290986/208118858-82c210f4-4010-4c36-acb6-c062dc0edfc3.jpeg) this is where I'm stock.

**Comment by danxtg** [comment]
> @danxtg whats your cost.... I don't mind paying ...![image](https://user-images.gith ubusercontent.com/120290986/208118858-82c210f4-4010-4c36-acb6-c062dc0edfc3.jpeg) this is where I'm stock.

okay

**Comment by yawacc** [comment]
> i have the solution now, but will cost $200

if the owner of the program demanded for money, would you have gotten it free? 
why are you greedy?

**Comment by danxtg** [comment]
What makes u think I got it free?, I got to find this platform during my
research after I encountered same issue, and I think git hub is supposed to
provide the Solution.... And am not selling any thing so you stop calling
me greedy.. Thanks

**Comment by yawacc** [comment]
who ever has the same issue should see this link for solution
https://github.com/alievk/avatarify-python/issues/484

**Comment by yawacc** [comment]
[https://github.com/alievk/avatarify-python/issues/484](url)

**Comment by yawacc** [comment]
who ever is having the same issue should find the solution on this page

https://github.com/alievk/avatarify-python/issues/484

**Comment by gpapi-afk** [comment]
![image](https://user-images.githubusercontent.com/121831388/210284413-7ad6e2fe-b569-469c-b67b-1aa316d626dd.jpg)

Please can anyone help me with this issue. I’d really appreciate.

**Comment by JohanAR** [comment]
@gpapi-afk that is not the same error as this issue is about. Use the search function to see if someone else has the same error as you, or create a new issue if there isn't. If you create a new issue, look up how to copy text from the terminal, and how to format it properly to make it readable on github. A photo of your screen makes it impossible for others to search for issues, so that should be avoided.

**Comment by gpapi-afk** [comment]
Please can you help me get my issue fixed? I could show it to you here and
you’re familiar with it. Please help me out.

**Comment by JohanAR** [comment]
I just told you how to get help.

This is not a chat, if you comment on this issue it must be related to *this* error/problem. I.e. "Cloning into 'fomm'... remote: Enumerating objects:". Any other errors go in different issues. If someone else has created an issue for your particular error, you should of course comment there.

Sorry if I sound a bit harsh but lately we've had an influx of people who are spamming their calls for help all over the place.

**Comment by NHJKLFYUY** [comment]
I have a problem help me sir, when I use avatarify, there is a bug and a slowness at the level of me and the clone, however the camera is fluid before I call on the double camera @JohanAR pls help me

**Comment by James65780166666** [comment]
![IMG_20230110_175053_979](https://user-imag.githubusercontent.com/122387645/211707054-eb1e4e43-f28b-48d7-b095-e6af6f3cb5c0.jpg)
Pl please help me sir I'm stuck here 🙏

**Comment by James65780166666** [comment]
![IMG_20230110_175053_979](https://user-images.githubusercontent.com/122387645/211707197-098039d7-7a63-4f59-b9bb-fa71a0971d8a.jpg)
Please help me out sir I'm stuck here 🙏🙏🙏
