### ISSUE TITLE
Corrupt vox-adv-cpk.pth.tar

### ISSUE THREAD

**Issue by Denvercraig** [alievk/avatarify-python#492]
**Describe the bug**

**initially the tar file has a 3 textbook icon but whenever I download it now it shows a regular file icon and that is the problem. Even if you move it into the right directory it’s still gonna show file not found**

**Info (please complete the following information):**
 - OS (windows 10 home): 
 - GPU model: GeForce 1660 ti,windows 10 home, 6gb graphics

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by JohanAR** [comment]
The docs has 3 different download links for this file, which one did you use? Did you follow the link, or right click -> save as... directly?

**Comment by NHJKLFYUY** [comment]
I too clicked on the link directly but I encounter the same problem so send me the link directly

**Comment by NHJKLFYUY** [comment]
I follow the instructions but it doesn't work and I can't get results because it fails

**Comment by fredrochel** [comment]
vox-adv-cpk.pth.tar  I can't download the file, it gives me an error each time I try to download

**Comment by JohanAR** [comment]
Did you try all 3 different download locations?

**Comment by fredrochel** [comment]
When I launch it does not ask me where I want to download it, I launch the
download each time when it comes to 400 it stops

**Comment by fredrochel** [comment]
can we discuss telegram I send you photos, I sincerely need help to succeed
in this programming.

Le jeu. 19 janv. 2023 à 9:51 AM, fred Anagonou ***@***.***> a
écrit :

**Comment by ogabwills** [comment]
Can vox-adv-cpk.pth.tar run on Intel Xeon processor? Because after I downloaded this and paste on the anaconda prompts, it does not show Intel Xeon but only corei7. Is there anything to be done?

**Comment by JohanAR** [comment]
vox-adv-cpk.pth.tar is a data file, it is not runnable. I'm guessing there is a bit of a language barrier but it's very unclear exactly what you have done. To run avatarify-python you need to follow each step of the installation instructions, and make sure that there wasn't any error before you proceed to the next them.

Closing this issue since the person who created it never came back, and it was likely a user error.

**Comment by ogabwills** [comment]
I’m sorry for not responding quickly.  I ran out of internet connection.  Maybe I didn’t put the question well initially.  I want to know if vox-adv-cpk.pth.tar works on Intel Xeon processor or is it only for corei7?

**Comment by JohanAR** [comment]
Your hardware should not matter for that particular file, as far as I know. However this is just a data file that is loaded by the avatarify-python program, did you mean to ask if avatarify-python runs on your computer? There are many different Xeon processors, it should run just fine on the newer ones. It is more important that you have an Nvidia graphics card. Check the documentation for minimum requirements.

Though if you know the program runs, but you actually have problems with the vox-adv-cpk.pth.tar file, perhaps your internet stopped working while downloading? It's a pretty large file, and I've seen others having this issue. The correct sha256 checksum for this file should be printed in the documentation, so you can verify that it downloaded without errors.

**Comment by ogabwills** [comment]
Yes, this is Avatarify-pythons program. Avatarify-python program runs on my computer but I can’t find  vox-adv-cpk.pth.tar that is compatible with the Xeon rather, I see only corei7.   I don’t know if my question is coming very clearly to you or not?  However, I’m so grateful for your responses.

**Comment by JohanAR** [comment]
Honestly I have no idea what you're doing. If you follow the instructions in the manual they will tell you where to download that file. The download links do not say anything about corei7, because this file has nothing to do with your CPU.

Are you trying to follow some other instructions? If you are following some other guide, ask the person who wrote it what they mean.
