### ISSUE TITLE
if you are facing this same issue, contact me, i have the solution.

### ISSUE THREAD

**Issue by yawacc** [alievk/avatarify-python#501]
[
![unnamed](https://user-images.githubusercontent.com/121608609/212538485-4c93aba1-f7ae-4170-814a-ab334f659691.jpg)

**Comment by JohanAR** [comment]
This is not a message board or chat site.

If you know how to solve this and want to help others, then post a reply to one of the open issues about it and/or submit a PR containing the fix. If not, take your business elsewhere.

**Comment by blaq777** [comment]
am having same issues, help me please
