### ISSUE TITLE
api.py:144: UserWarning: No faces were detected.   warnings.warn("No faces were detected.")

### ISSUE THREAD

**Issue by Tesrocha22** [alievk/avatarify-python#507]
I'm new to Git & Avatarify-python and hardly know my way around, i have been trying to, the Avatarify app itself functions fine, but when i enter commands it displays below

![Screenshot (1)](https://user-images.githubusercontent.com/123034008/213411915-f975a429-4532-40e2-9d4d-03772f4b2528.png)

(base) C:\Users\efeos>git clone https://github.com/alievk/avatarify-python.git
fatal: destination path 'avatarify-python' already exists and is not an empty directory.

(base) C:\Users\efeos>cd avatarify-python

(base) C:\Users\efeos\avatarify-python>scripts\install_windows.bat
conda found
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: C:\Users\efeos\miniconda3\envs\avatarify

  added / updated specs:
    - python=3.7

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2022.10.11-haa95532_0
  certifi            pkgs/main/win-64::certifi-2022.12.7-py37haa95532_0
  openssl            pkgs/main/win-64::openssl-1.1.1s-h2bbff1b_0
  pip                pkgs/main/win-64::pip-22.3.1-py37haa95532_0
  python             pkgs/main/win-64::python-3.7.16-h6244533_0
  setuptools         pkgs/main/win-64::setuptools-65.6.3-py37haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.40.1-h2bbff1b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37haa95532_2

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate avatarify
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: C:\Users\efeos\miniconda3\envs\avatarify

  added / updated specs:
    - numpy==1.19.0
    - python-blosc==1.7.0
    - scikit-image

The following NEW packages will be INSTALLED:

  blosc              conda-forge/win-64::blosc-1.21.1-h74325e0_3
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  c-blosc2           conda-forge/win-64::c-blosc2-2.3.1-hdf67494_0
  cfitsio            conda-forge/win-64::cfitsio-4.0.0-hd67004f_0
  charls             conda-forge/win-64::charls-2.3.4-h39d44d4_0
  cloudpickle        conda-forge/noarch::cloudpickle-2.2.0-pyhd8ed1ab_0
  cytoolz            conda-forge/win-64::cytoolz-0.12.0-py37hcc03f2d_0
  dask-core          conda-forge/noarch::dask-core-2022.2.0-pyhd8ed1ab_0
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0
  freetype           conda-forge/win-64::freetype-2.12.1-h546665d_0
  fsspec             conda-forge/noarch::fsspec-2022.11.0-pyhd8ed1ab_0
  giflib             conda-forge/win-64::giflib-5.2.1-h8d14728_2
  imagecodecs        conda-forge/win-64::imagecodecs-2021.11.20-py37hfea8715_2
  imageio            conda-forge/noarch::imageio-2.24.0-pyh24c5eb1_0
  intel-openmp       conda-forge/win-64::intel-openmp-2023.0.0-h57928b3_25922
  jpeg               conda-forge/win-64::jpeg-9e-h8ffe710_2
  jxrlib             conda-forge/win-64::jxrlib-1.1-h8ffe710_2
  krb5               conda-forge/win-64::krb5-1.19.3-h1176d77_0
  lcms2              conda-forge/win-64::lcms2-2.12-h2a16943_0
  lerc               conda-forge/win-64::lerc-3.0-h0e60522_0
  libaec             conda-forge/win-64::libaec-1.0.6-h39d44d4_0
  libblas            conda-forge/win-64::libblas-3.9.0-16_win64_mkl
  libbrotlicommon    conda-forge/win-64::libbrotlicommon-1.0.9-h8ffe710_7
  libbrotlidec       conda-forge/win-64::libbrotlidec-1.0.9-h8ffe710_7
  libbrotlienc       conda-forge/win-64::libbrotlienc-1.0.9-h8ffe710_7
  libcblas           conda-forge/win-64::libcblas-3.9.0-16_win64_mkl
  libcurl            conda-forge/win-64::libcurl-7.83.1-h789b8ee_0
  libdeflate         conda-forge/win-64::libdeflate-1.10-h8ffe710_0
  liblapack          conda-forge/win-64::liblapack-3.9.0-16_win64_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-h1d00b33_4
  libssh2            conda-forge/win-64::libssh2-1.10.0-h680486a_3
  libtiff            conda-forge/win-64::libtiff-4.4.0-hc4061b1_0
  libwebp-base       conda-forge/win-64::libwebp-base-1.2.4-h8ffe710_0
  libxcb             conda-forge/win-64::libxcb-1.13-hcd874cb_1004
  libzlib            conda-forge/win-64::libzlib-1.2.12-h8ffe710_2
  libzopfli          conda-forge/win-64::libzopfli-1.0.3-h0e60522_0
  locket             conda-forge/noarch::locket-1.0.0-pyhd8ed1ab_0
  lz4-c              conda-forge/win-64::lz4-c-1.9.3-h8ffe710_1
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  mkl                conda-forge/win-64::mkl-2022.1.0-h6a75c08_874
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  networkx           conda-forge/noarch::networkx-2.5-py_0
  numpy              conda-forge/win-64::numpy-1.19.0-py37hae9e721_0
  openjpeg           conda-forge/win-64::openjpeg-2.5.0-hc9384bd_1
  packaging          conda-forge/noarch::packaging-23.0-pyhd8ed1ab_0
  partd              conda-forge/noarch::partd-1.3.0-pyhd8ed1ab_0
  pillow             conda-forge/win-64::pillow-9.2.0-py37h42a8222_2
  pthread-stubs      conda-forge/win-64::pthread-stubs-0.4-hcd874cb_1001
  python-blosc       conda-forge/win-64::python-blosc-1.7.0-py37h6538335_1001
  python_abi         conda-forge/win-64::python_abi-3.7-2_cp37m
  pywavelets         conda-forge/win-64::pywavelets-1.3.0-py37hec80d1f_0
  pyyaml             conda-forge/win-64::pyyaml-6.0-py37hcc03f2d_4
  scikit-image       conda-forge/win-64::scikit-image-0.19.2-py37h9386db6_0
  scipy              conda-forge/win-64::scipy-1.7.3-py37hb6553fb_0
  snappy             conda-forge/win-64::snappy-1.1.9-h82413e6_1
  tbb                conda-forge/win-64::tbb-2021.5.0-h2d74725_1
  tifffile           conda-forge/noarch::tifffile-2021.11.2-pyhd8ed1ab_0
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  toolz              conda-forge/noarch::toolz-0.12.0-pyhd8ed1ab_0
  xorg-libxau        conda-forge/win-64::xorg-libxau-1.0.9-hcd874cb_0
  xorg-libxdmcp      conda-forge/win-64::xorg-libxdmcp-1.1.3-hcd874cb_0
  xz                 conda-forge/win-64::xz-5.2.6-h8d14728_0
  yaml               conda-forge/win-64::yaml-0.2.5-h8ffe710_2
  zfp                conda-forge/win-64::zfp-0.5.5-h0e60522_8
  zlib-ng            conda-forge/win-64::zlib-ng-2.0.6-h8ffe710_0
  zstd               conda-forge/win-64::zstd-1.5.2-h6255e5f_4

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2022.10.11~ --> conda-forge::ca-certificates-2022.12.7-h5b45459_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main/win-64::certifi-2022.12.7-p~ --> conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: C:\Users\efeos\miniconda3\envs\avatarify

  added / updated specs:
    - cudatoolkit=11.0
    - pytorch==1.7.1
    - torchvision

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  cudatoolkit        pkgs/main/win-64::cudatoolkit-11.0.221-h74a9793_0
  flit-core          pkgs/main/noarch::flit-core-3.6.0-pyhd3eb1b0_0
  libuv              pkgs/main/win-64::libuv-1.40.0-he774522_0
  ninja              pkgs/main/win-64::ninja-1.10.2-haa95532_5
  ninja-base         pkgs/main/win-64::ninja-base-1.10.2-h6d14046_5
  pytorch            pytorch/win-64::pytorch-1.7.1-py3.7_cuda110_cudnn8_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
  torchvision        pytorch/noarch::torchvision-0.2.2-py_3
  typing_extensions  pkgs/main/win-64::typing_extensions-4.4.0-py37haa95532_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            conda-forge/noarch::certifi-2022.12.7~ --> pkgs/main/win-64::certifi-2022.12.7-py37haa95532_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting package metadata (current_repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

## Package Plan ##

  environment location: C:\Users\efeos\miniconda3\envs\avatarify

  added / updated specs:
    - git

The following NEW packages will be INSTALLED:

  git                anaconda/win-64::git-2.34.1-haa95532_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2022.12.~ --> anaconda::ca-certificates-2022.4.26-haa95532_0
  certifi            pkgs/main::certifi-2022.12.7-py37haa9~ --> anaconda::certifi-2022.6.15-py37haa95532_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Cloning into 'fomm'...
remote: Enumerating objects: 211, done.
remote: Total 211 (delta 0), reused 0 (delta 0), pack-reused 211R
Receiving objects: 100% (211/211), 58.16 MiB | 3.52 MiB/s, done.
Resolving deltas: 100% (108/108), done.
Updating files: 100% (44/44), done.

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

option --use-feature: invalid choice: '2020-resolver' (choose from 'fast-deps', 'truststore', 'no-binary-enable-wheel-cache')

(avatarify) C:\Users\efeos\avatarify-python>pip install pyyaml
Requirement already satisfied: pyyaml in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (6.0)

(avatarify) C:\Users\efeos\avatarify-python>pip install requests
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from requests) (2022.6.15)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.0.1-cp37-cp37m-win_amd64.whl (94 kB)
Installing collected packages: charset-normalizer, urllib3, idna, requests
Successfully installed charset-normalizer-3.0.1 idna-3.4 requests-2.28.2 urllib3-1.26.14

(avatarify) C:\Users\efeos\avatarify-python>pip install face_alignment
Collecting face_alignment
  Using cached face_alignment-1.3.5-py2.py3-none-any.whl
Requirement already satisfied: scipy>=0.17 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from face_alignment) (1.7.3)
Collecting numba
  Using cached numba-0.56.4-cp37-cp37m-win_amd64.whl (2.5 MB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting opencv-python
  Using cached opencv_python-4.7.0.68-cp37-abi3-win_amd64.whl (38.2 MB)
Requirement already satisfied: numpy in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from face_alignment) (1.19.0)
Requirement already satisfied: scikit-image in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from face_alignment) (0.19.2)
Requirement already satisfied: torch in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from face_alignment) (1.7.1)
Collecting importlib-metadata
  Using cached importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
Collecting llvmlite<0.40,>=0.39.0dev0
  Using cached llvmlite-0.39.1-cp37-cp37m-win_amd64.whl (23.2 MB)
Requirement already satisfied: setuptools in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from numba->face_alignment) (65.6.3)
Requirement already satisfied: networkx>=2.2 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from scikit-image->face_alignment) (2.5)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from scikit-image->face_alignment) (2021.11.2)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from scikit-image->face_alignment) (1.3.0)
Requirement already satisfied: imageio>=2.4.1 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from scikit-image->face_alignment) (2.24.0)
Requirement already satisfied: packaging>=20.0 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from scikit-image->face_alignment) (23.0)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from scikit-image->face_alignment) (9.2.0)
Requirement already satisfied: typing_extensions in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from torch->face_alignment) (4.4.0)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: decorator>=4.3.0 in c:\users\efeos\miniconda3\envs\avatarify\lib\site-packages (from networkx>=2.2->scikit-image->face_alignment) (5.1.1)
Collecting zipp>=0.5
  Using cached zipp-3.11.0-py3-none-any.whl (6.6 kB)
Installing collected packages: zipp, opencv-python, llvmlite, colorama, tqdm, importlib-metadata, numba, face_alignment
Successfully installed colorama-0.4.6 face_alignment-1.3.5 importlib-metadata-6.0.0 llvmlite-0.39.1 numba-0.56.4 opencv-python-4.7.0.68 tqdm-4.64.1 zipp-3.11.0

(avatarify) C:\Users\efeos\avatarify-python>run_windows.bat
[1674119032.798138] Loading Predictor
C:\Users\efeos\miniconda3\envs\avatarify\lib\site-packages\torch\nn\functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "

=== Control keys ===
1-9: Change avatar
1: avatars\199.jpg
2: avatars\204.jpg
3: avatars\53.jpg
4: avatars\einstein.jpg
W: Zoom camera in
S: Zoom camera out
A: Previous avatar in folder
D: Next avatar in folder
Q: Get random avatar
X: Calibrate face pose
I: Show FPS
ESC: Quit

Full key list: https://github.com/alievk/avatarify#controls

C:\Users\efeos\miniconda3\envs\avatarify\lib\site-packages\face_alignment\api.py:144: UserWarning: No faces were detected.
  warnings.warn("No faces were detected.")
C:\Users\efeos\miniconda3\envs\avatarify\lib\site-packages\torch\nn\functional.py:3385: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_
![Screenshot (1)](https://user-images.githubusercontent.com/123034008/213406874-67ce3fc1-cb5b-4e9c-b016-d7e021879a45.png)
sample and affine_grid behavior has changed "
C:\Users\efeos\miniconda3\envs\avatarify\lib\site-packages\torch\nn\functional.py:1639: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")

**Comment by JohanAR** [comment]
The window that is gray with a red square is supposed to show the video from your webcam. Maybe your webcam is not supported by OpenCV (which is what avatarify-python uses).

Have you tried https://github.com/alievk/avatarify-desktop ? It uses a different library for the webcam, so it might work.

**Comment by JohanAR** [comment]
No reply from issue author
