### ISSUE TITLE
Installation on miniconda, 

### ISSUE THREAD

**Issue by mtee4real87** [alievk/avatarify-python#519]
I am stalk, its been solving enviroment for about 3 hours now, solution please

**Comment by JohanAR** [comment]
If you want someone to be able to help you, write a proper issue report.

**Comment by richmind1** [comment]
please i need help, on the minicodo its till solving enviroment for hours please help what should i do. in using hp zbook studio 15 g3 core i7 4gb dedicator nvidia 16gb ram 512ssd. please help me my whatsapp number is +2348100867220...

**Comment by richmind1** [comment]
openssl            pkgs/main/win-64::openssl-1.1.1t-h2bbff1b_0
  pip                pkgs/main/win-64::pip-22.3.1-py37haa95532_0
  python             pkgs/main/win-64::python-3.7.16-h6244533_0
  setuptools         pkgs/main/win-64::setuptools-65.6.3-py37haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.40.1-h2bbff1b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/win-64::wheel-0.38.4-py37haa95532_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37haa95532_2



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate avatarify
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: |

**Comment by richmind1** [comment]
please help me here
