### ISSUE TITLE
i've been here for hoursand have good internet please what is wrong

### ISSUE THREAD

**Issue by ridwan221291** [alievk/avatarify-python#521]
![Screenshot 2023-03-06 055537](https://user-images.githubusercontent.com/127054016/222988177-3f8bd510-ee99-43f2-8959-bd7ecacd7654.png)

**Comment by Kashfrank** [comment]
Have you solved this

**Comment by richmind1** [comment]
i also please help

**Comment by FrancisKC** [comment]
> Have you solved this

I have the same problem too 😩

**Comment by JohanAR** [comment]
Title does not describe the issue. Has a screen shot instead of actual log. It's pretty bad issue report in other words. Use #526 instead.
