### ISSUE TITLE
ModuleNotFoundError: No module name 'modules.keypoint_detector'; 'module' is not a package

### ISSUE THREAD

**Issue by zadkeilpaul** [alievk/avatarify-python#530]
I got this error 

Traceback (most recent call last:) 

File "afy/cam_fomm.py, line 216, in <module> from afy  import predictor_local File " 

(C:\Yungm\avatarify-python-youtube\afy\predictor_local.py", line 4, in <module> 

ModuleNotFoundError: No module name 'modules.keypoint_detector'; 'module' is not a package

Windows 11
RTX 3070

![IMG_20230311_143023_3_1678722159472](https://user-images.githubusercontent.com/127767227/224872199-a89a4e45-14bf-4016-80bd-2c9c6a541648.jpg)

**Comment by JohanAR** [comment]
avatarify-python-youtube is a different repository. Report the issue with them.
