### ISSUE TITLE
Solving environment 

### ISSUE THREAD

**Issue by FrancisKC** [alievk/avatarify-python#531]
**Describe the bug**

It takes about 5-6 hours to solve environment, please is there any workaround?
**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux):  windows 11
 - GPU model: Gtx 1650

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by JohanAR** [comment]
Reported in #526 and other issues.
