### ISSUE TITLE
I run the last command but it still didn't work@XpliDGhost Yes run the last comment after everything run_windows.bat

### ISSUE THREAD

**Issue by XpliDGhost** [alievk/avatarify-python#550]
@XpliDGhost Yes run the last comment after everything run_windows.bat

_Originally posted by @Jblaac7 in https://github.com/alievk/avatarify-python/issues/523#issuecomment-1464068622_

I did it but it keep showing me same error

**Comment by JohanAR** [comment]
This is an issue tracker, not a message board. If you want to reply to someone, do it in the relevant issue.

Otherwise follow the new issue template if you want to report an issue that has not been reported yet.
