### ISSUE TITLE
scripts\install_windows.bat

### ISSUE THREAD

**Issue by ostronic** [alievk/avatarify-python#556]
Why is scripts\install_windows.bat taking too long to install more than 2 hrs now not yet done 
![16803935021152379034006731725399](https://user-images.githubusercontent.com/67126122/229323368-6fb7edee-acbe-407d-9add-408cffcaf4b3.jpg)

**Comment by JohanAR** [comment]
1) Check existing open issues
2) Don't post a photo of your monitor. If you want someone to spend their free time helping you, at least make the effort to write a usable issue report.
