### ISSUE TITLE
Installation not successful 

### ISSUE THREAD

**Issue by workingnike** [alievk/avatarify-python#560]
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
The system cannot find the file specified.
Cloning into 'fomm'...
remote: Enumerating objects: 211, done.
remote: Total 211 (delta 0), reused 0 (delta 0), pack-reused 211
Receiving objects: 100% (211/211), 58.16 MiB | 7.59 MiB/s, done.
Resolving deltas: 100% (108/108), done.

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

option --use-feature: invalid choice: '2020-resolver' (choose from 'fast-deps', 'truststore', 'no-binary-enable-wheel-cache')

**Comment by workingnike** [comment]
Where can we get the actual thing to down because after waiting for hours and this is not good

**Comment by JohanAR** [comment]
Check existing issue reports related to "2020-resolver" error.
