### ISSUE TITLE
conda

### ISSUE THREAD

**Issue by songjoongki123** [alievk/avatarify-python#571]
**Describe the bug**

**To Reproduce**

**Info (please complete the following information):**
 - OS (e.g., Linux): 
 - GPU model: 

 - Any other relevant information: 

**Screenshots**

**Logs**

**Comment by Chinky007** [comment]
I’m using Win 11
GPU : Nividia GeForce RTX 3050
![Uploading F030EE98-C306-412C-9D03-DD978B85501C.jpeg…]()
