### ISSUE TITLE
Available to help 

### ISSUE THREAD

**Issue by ostronic** [alievk/avatarify-python#595]
I AM AVAILABLE TO HELP ANYONE HAVING ISSUES INSTALLING AVATARIFY ON WINDOWS PC.
HMU ON TELEGRAM @Qxchan
Please go straight to the point ‼️

**Comment by MomoDbg** [comment]
I did all right but the process stuck at 'solving environment'... what can I do ?

**Comment by JohanAR** [comment]
@MomoDbg use the search function and look for reported issues containing the phrase "solving environments".
