### ISSUE TITLE
The checkpoints file has been downloaded automatically, but it cannot be found

### ISSUE THREAD

**Issue by java43wuyi** [alievk/avatarify-python#604]
The checkpoints file has been downloaded automatically, but it cannot be found.RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\这台电脑/.cache\torch\hub\checkpoints\2DFAN4-cd938726ad.zip.The file was found when I pasted the address into the Windows system location bar.

**Comment by JohanAR** [comment]
It might have problems with the characters in your user name, I think I've seen people issues with Cyrillic characters in their user name. Don't know if it's possible to move the cache folder to somewhere else

**Comment by java43wuyi** [comment]
I set Torch Home in "E:/" in the Windows system path, which solved the problem

**Comment by JohanAR** [comment]
Glad to hear the issue was solved!
