### ISSUE TITLE
"avatarify desktop" does not work

### ISSUE THREAD

**Issue by mv6677** [alievk/avatarify-python#624]
Hello.
I have a problem.
I'm running "avatarify desktop" on windows 10, but the program doesn't open. 
In Task Manager, the process is present, but the interface of the "avatarify desktop" program does not open. 
RTX3060 graphics card, DDR4 128Gb, Intel Core i9.

**Comment by JohanAR** [comment]
Please open an issue on the Avatarify Desktop project issue tracker in that case, this is avatarify-python which is an older cross-platform version of Avatarify.
