### ISSUE TITLE
changing cam default for google collab 

### ISSUE THREAD

**Issue by trustjosh705** [alievk/avatarify-python#649]
Hello alievk, how can I change my camera default on the google collab avatarify to the cam I want, I need you to help me out with this.

**Comment by SanPatrick01** [comment]
Go to the avatarify folder and locate cam or cam.yaml open to edit it 
Change the cam ID from 0 to 1 or 1 to 0 save and close it

**Comment by trustjosh705** [comment]
thanks it worked
