### ISSUE TITLE
 File "afy/cam_fomm.py", line 217, in <module>

### ISSUE THREAD

**Issue by JasonCole230** [alievk/avatarify-python#663]
I need help getting past this error while trying to run Avatarify on Windows 10
 
C:\Users\USER\miniconda3\envs\avatarify\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 217, in <module>
    predictor = predictor_local.PredictorLocal(
  File "C:\Users\USER\avatarify-python\afy\predictor_local.py", line 49, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
  File "C:\Users\USER\miniconda3\envs\avatarify\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by SanPatrick01** [comment]
Check my video on YouTube

**Comment by solid-cmd** [comment]
Make sure you have the following installed
Visualstudiosetup
Cuda
Vc_redist.x64

Locate miniconda3/env and delete all the directories there

Locate your avatarify-python directory make sure fomm directory is there

Open miniconda and do these;
Cd avatarify-python
create a new environment with this

Conda create -n pass
(you can use any name, it's of no use but will help with manual installation)
Then type
Scripts\install_windows.bat

When you get to the solving environment that kills all the time hit
Carl+c
You get (y/n) hit n
Installation will begin

Let it run and yes you will get other error

Now type
Pip install -r requirements.txt

Let it all install

Then put your vox file in the avatarify-python directory

Then type
Run_windows.bat

You get another error

Then do this
Pip Install pillow==9.5.0

Then
Run_windows.bat

This time it all works well

**Comment by JasonCole230** [comment]
> Make sure you have the following installed Visualstudiosetup Cuda Vc_redist.x64
> 
> Locate miniconda3/env and delete all the directories there
> 
> Locate your avatarify-python directory make sure fomm directory is there
> 
> Open miniconda and do these; Cd avatarify-python create a new environment with this
> 
> Conda create -n pass (you can use any name, it's of no use but will help with manual installation) Then type Scripts\install_windows.bat
> 
> When you get to the solving environment that kills all the time hit Carl+c You get (y/n) hit n Installation will begin
> 
> Let it run and yes you will get other error
> 
> Now type Pip install -r requirements.txt
> 
> Let it all install
> 
> Then put your vox file in the avatarify-python directory
> 
> Then type Run_windows.bat
> 
> You get another error
> 
> Then do this Pip Install pillow==9.5.0
> 
> Then Run_windows.bat
> 
> This time it all works well

Thank You, mate.
