### ISSUE TITLE
KMP_DUPLICATE_LIB_OK=TRUE 

### ISSUE THREAD

**Issue by GitHub1342** [alievk/avatarify-python#677]
[1699106905.376770] Loading Predictor
C:\Users\kamti\miniconda3\envs\avatarify\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by SanPatrick01** [comment]
Go to your users directory 
On the top right concern 
Paste this in the search box libiomp5md.dll

And delete the one with library/bin at the end 
If you didn't get it well 
Check my video Avatarify easy installation
https://youtu.be/nW5_-zPVmec

**Comment by SanPatrick01** [comment]
Or send anydesk to WhatsApp ‪+234 811 513 3627‬

**Comment by Updatedme** [comment]
> [1699106905.376770] Loading Predictor
> C:\Users\kamti\miniconda3\envs\avatarify\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3527.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

If you have any problem with avatarify . Contact me for solutions 100% results on apple macbook and any windows.
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by Updatedme** [comment]
> [1699106905.376770] Loading Predictor
> C:\Users\kamti\miniconda3\envs\avatarify\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3527.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

If you have any problem with avatarify . Contact me for solutions 100% results on apple macbook and any windows.
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010

**Comment by Updatedme** [comment]
If you have any problem with avatarify . Contact me for solutions 100% results on apple macbook and any windows.
You can also watch my installation video that shows you how to do it yourself. Or simply ask for help from my whatsapp contact 
https://wa.me/message/GXQYWX4XRTXGB1
+2347081306010
